//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.5477
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

/// This class was created from file F:\Components\DiseasesComponent\Nuova architettura\CRA.DiseaseProgress\CRA.Diseases.Airborne.DiseaseProgress.Interfaces\XML files\Rates.xml
/// DCC - Domain Class Coder, http://agsys.cra-cin.it/tools , see Applications, DCC
// 

using CRA.ModelLayer.ParametersManagement;

namespace CRA.Diseases.Airborne.DiseaseProgress.Interfaces
{
    using System;
    using System.Collections.Generic;
    using CRA.ModelLayer.Core;
    using System.Reflection;
    
    
    
    /// <summary>Rates Domain class contains the accessors to values</summary>
    public class Rates : ICloneable, IDomainClass
    {
        
        #region Private fields
        private double _HostTissueLatentDaily;
        
        private double _HostTissueVisibleDaily;
        
        private double _HostTissueInfectiousDaily;
        
        private double _HostTissueOldDaily;
        
        private double _IncubationProgressDaily;
        
        private double _LatencyProgressDaily;
        
        private double _InfectiousnessProgressDaily;
        
        private double _InfectionDaily;
        
        private double _HostTissueDiseasedDaily;
        
        private double _HostTissueAffectedDaily;
        
        private double _DiseaseInfectionCompositeIndex;
        #endregion
        
        #region Private field for properties
        private ParametersIO _parametersIO;
        #endregion
        
        #region Constructor
        /// <summary>No parameters constructor</summary>
        public Rates()
        {
            _parametersIO = new ParametersIO(this);
        }
        #endregion
        
        #region Public properties
        /// <summary>Progress rate of the host tissue with latent infections.</summary>
        public double HostTissueLatentDaily
        {
            get
            {
                return this._HostTissueLatentDaily;
            }
            set
            {
                this._HostTissueLatentDaily = value;
            }
        }
        
        /// <summary>Progress rate of the host tissue with visible lesions.</summary>
        public double HostTissueVisibleDaily
        {
            get
            {
                return this._HostTissueVisibleDaily;
            }
            set
            {
                this._HostTissueVisibleDaily = value;
            }
        }
        
        /// <summary>Progress rate of the host tissue with infectious lesions.</summary>
        public double HostTissueInfectiousDaily
        {
            get
            {
                return this._HostTissueInfectiousDaily;
            }
            set
            {
                this._HostTissueInfectiousDaily = value;
            }
        }
        
        /// <summary>Progress rate of the host tissue with lesion old and sterile.</summary>
        public double HostTissueOldDaily
        {
            get
            {
                return this._HostTissueOldDaily;
            }
            set
            {
                this._HostTissueOldDaily = value;
            }
        }
        
        /// <summary>Progress rate of incubation.</summary>
        public double IncubationProgressDaily
        {
            get
            {
                return this._IncubationProgressDaily;
            }
            set
            {
                this._IncubationProgressDaily = value;
            }
        }
        
        /// <summary>Progress rate of latency.</summary>
        public double LatencyProgressDaily
        {
            get
            {
                return this._LatencyProgressDaily;
            }
            set
            {
                this._LatencyProgressDaily = value;
            }
        }
        
        /// <summary>Progress rate of infectiousness.</summary>
        public double InfectiousnessProgressDaily
        {
            get
            {
                return this._InfectiousnessProgressDaily;
            }
            set
            {
                this._InfectiousnessProgressDaily = value;
            }
        }
        
        /// <summary>Progress rate of infection.</summary>
        public double InfectionDaily
        {
            get
            {
                return this._InfectionDaily;
            }
            set
            {
                this._InfectionDaily = value;
            }
        }
        
        /// <summary>Progress rate of the host tissue diseased</summary>
        public double HostTissueDiseasedDaily
        {
            get
            {
                return this._HostTissueDiseasedDaily;
            }
            set
            {
                this._HostTissueDiseasedDaily = value;
            }
        }
        
        /// <summary>Progress rate of the host tissue affected</summary>
        public double HostTissueAffectedDaily
        {
            get
            {
                return this._HostTissueAffectedDaily;
            }
            set
            {
                this._HostTissueAffectedDaily = value;
            }
        }
        
        /// <summary>Disease infection composite index rate</summary>
        public double DiseaseInfectionCompositeIndex
        {
            get
            {
                return this._DiseaseInfectionCompositeIndex;
            }
            set
            {
                this._DiseaseInfectionCompositeIndex = value;
            }
        }
        #endregion
        
        #region IDomainClass members
        /// <summary>Domain Class description</summary>
        public virtual  string Description
        {
            get
            {
                return "Domain classRatesVarInfo Rate variables of DiseasesProgress component";
            }
        }
        
        /// <summary>Domain Class URL</summary>
        public virtual  string URL
        {
            get
            {
                return "http://";
            }
        }
        
        /// <summary>Domain Class Properties</summary>
        public virtual IDictionary<string, PropertyInfo> PropertiesDescription
        {
            get
            {
                return _parametersIO.GetCachedProperties(typeof(IDomainClass));
            }
        }
        #endregion
        
        /// <summary>Clears the values of the properties of the domain class by using the default value for the type of each property (e.g '0' for numbers, 'the empty string' for strings, etc.)</summary>
        public virtual Boolean ClearValues()
        {
            _HostTissueLatentDaily = default(System.Double);
            _HostTissueVisibleDaily = default(System.Double);
            _HostTissueInfectiousDaily = default(System.Double);
            _HostTissueOldDaily = default(System.Double);
            _IncubationProgressDaily = default(System.Double);
            _LatencyProgressDaily = default(System.Double);
            _InfectiousnessProgressDaily = default(System.Double);
            _InfectionDaily = default(System.Double);
            _HostTissueDiseasedDaily = default(System.Double);
            _HostTissueAffectedDaily = default(System.Double);
            _DiseaseInfectionCompositeIndex = default(System.Double);
            // Returns true if everything is ok
            return true;
        }
        
        #region Clone
        /// <summary>Implement ICloneable.Clone()</summary>
        public virtual Object Clone()
        {
            // Shallow copy by default
            IDomainClass myclass = (IDomainClass) this.MemberwiseClone();
            _parametersIO.PopulateClonedCopy(myclass);
            return myclass;
        }
        #endregion
    }
}
